### ISSUE TITLE
设置面板的异常白色条纹

### ISSUE THREAD

**Issue by frostime** [mdzz2048/Lite#11]
设置面板的分隔符是通过 box-shadow 实现的，由于主题重写了背景颜色，导致出现了异常的白色条纹

![image](https://github.com/mdzz2048/Lite/assets/27268127/a9368b66-01d0-4494-a1b6-c4a205aa0f54)

**Comment by mdzz2048** [comment]
感谢反馈，上次发版的时候 theme.json 忘了更新了，这个问题之前修复过的（ https://github.com/mdzz2048/Lite/commit/5df773416ae6991883d4a699c55136fb77dfb739 ）
