### ISSUE TITLE
Bug：在独立小窗口下打开多个标签页会导致无法拖动窗口

### ISSUE THREAD

**Issue by frostime** [mdzz2048/Lite#4]
已经禁用了全部插件，确定是主题的问题。

复现步骤：

1. 在新窗口当中打开一个文档

    此时页面还正常
  
    ![image](https://github.com/mdzz2048/Lite/assets/27268127/c9a87084-5681-480f-932e-1cfd3629cdf0)

2. 然后在新窗口再次打开一个页签（比如 Ctrl + 点击一个链接）

此时 bug 触发，顶栏无法拖动移动窗口

![image](https://github.com/mdzz2048/Lite/assets/27268127/bf934e2c-64b2-459c-9e23-52b99de6261e)

**Comment by mdzz2048** [comment]
感谢反馈，定位到问题了，下版本修复
