### ISSUE TITLE
子弹线和导图插件的样式存在严重冲突

### ISSUE THREAD

**Issue by frostime** [mdzz2048/Lite#5]
![image](https://github.com/mdzz2048/Lite/assets/27268127/1eb53d40-7c1e-47e4-9b27-163b6ddea1c6)

建议：
- 要么暂时去掉这个样式
- 要么和savor那样做成可选项目，可以打开也可以关闭（不过这个就会引入多余的 Js 了）

**Comment by mdzz2048** [comment]
收到，下版本改进：
1. 增加全局列表子弹线开关
2. 支持文档通过自定义属性开关子弹线样式

**Comment by mdzz2048** [comment]
文档级别禁用：设置自定义属性 custom-list-bullet="false"
