### ISSUE TITLE
闪卡复习时标记一直遮挡

### ISSUE THREAD

**Issue by gaoluji** [mdzz2048/Lite#7]
![image](https://github.com/mdzz2048/Lite/assets/139356383/25d1c74f-2def-4e83-9ebb-675b4f279375)

**Comment by mdzz2048** [comment]
感谢反馈，下版本修复

**Comment by gaoluji** [comment]
> 感谢反馈，下版本修复

闪卡虽然能显示了，但文档里面显示不了了

**Comment by mdzz2048** [comment]
主题按钮里的“标记样式”关掉了吗？现在的“标记样式”是在文档里隐藏标记

**Comment by gaoluji** [comment]
> 主题按钮里的“标记样式”关掉了吗？现在的“标记样式”是在文档里隐藏标记

我把软件重启了一下，可以了

**Comment by gaoluji** [comment]
> 主题按钮里的“标记样式”关掉了吗？现在的“标记样式”是在文档里隐藏标记

还是不行，开了之后虽然文档上能显示了，但闪卡又显示不了了

**Comment by gaoluji** [comment]
> 主题按钮里的“标记样式”关掉了吗？现在的“标记样式”是在文档里隐藏标记

![image](https://github.com/mdzz2048/Lite/assets/139356383/d90913f1-1594-4963-8084-0eeeee30f8c0)
![image](https://github.com/mdzz2048/Lite/assets/139356383/e8815f13-2c9e-4605-8e10-23d2063340e1)

**Comment by mdzz2048** [comment]
闪卡样式也得关掉，昨天忘了改了
