### ISSUE TITLE
2.10.13版本代码块无法正常查看

### ISSUE THREAD

**Issue by tinyxb** [mdzz2048/Lite#8]
[https://ld246.com/article/1698981078241](https://ld246.com/article/1698981078241)

**Comment by tinyxb** [comment]
<img width="941" alt="SCR-20231103-mowe" src="https://github.com/mdzz2048/Lite/assets/2309374/ce965161-bdc1-459f-929c-4fbee3646981">

**Comment by mdzz2048** [comment]
v1.1.4 已修复
