### ISSUE TITLE
代码块显示异常

### ISSUE THREAD

**Issue by frostime** [mdzz2048/Lite#9]
![image](https://github.com/mdzz2048/Lite/assets/27268127/767644f6-0079-4211-af57-770fb64e3ba7)

https://ld246.com/article/1698981078241

**Comment by mdzz2048** [comment]
v1.1.4 是修复了的，不过我不太清楚为啥 theme.json 和 release 都改了思源集市还是 v1.1.3 的……
我一会再发一版吧。

**Comment by frostime** [comment]
![image](https://github.com/mdzz2048/Lite/assets/27268127/5ae6af69-0890-48bb-88a9-0e3c9ad3806a)

json 格式里还是 1.1.3

**Comment by mdzz2048** [comment]
应该是我上次提交操作顺序错了，新版本已发布
